### ISSUE TITLE
Issues with boolean operators

### ISSUE THREAD

**Issue by poison** [alexeyrybak/blitz#20]
1) Comparing a string with a null-variable is always true
2) Using a string with a boolean (eg; IF var && (a == b)) doesn't work when intval(var) = 0 (even though it's a non-empty string like 'bananas')

**Comment by poison** [comment]
Should be resolved in PR #21 (added tests as well)

**Comment by alexeyrybak** [comment]
Nicolas, I'm afraid that this fix adds a problem with string comparison again, my fault - I didn't add tests in 0.8.18 but could you please clarify that, thanks.

**Comment by alexeyrybak** [comment]
more details from http://alexeyrybak.com/blitz/bt/view.php?id=333

fisher	(administrator) 
2015-03-06 01:04
edited on: 2015-03-06 01:05

  
bug!

<?
$c = 'textarea';
$d = !$c;
echo '!C IS:', "\n";
var_dump($d);
$T = new Blitz();
$T->load("{{IF !c}} !C IS TRUE {{ELSE}} !C IS FALSE {{END}}");
$T->display(array('c' => $c));


...

[EXEC] node:IF, pos = 0, lc = 0, next = 0x10f6ec5f8
*** FUNCTION *** blitz_exec_if_context
*** FUNCTION *** blitz_check_expr argcnt=2
operands c type#0 = <UNKNOWN>(3) (dval:0.000000 sval:textarea(len=8))
using double variable for the NOT operator
checking context IF (type=94, args=2)
condition = 1, is_true = 1

(0000527)
fisher	(administrator) 
2015-03-06 01:34

  
fixed in 0.8.18
